services:
  backend:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: .
      args:
        DB_URL: jdbc:postgresql://database:5432/sabores-conectados
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend-network
    ports:
      - 8081:8080
    restart: on-failure:3

  database:
    image: postgres:13.21-alpine3.20
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=sabores-conectados
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - 5432:5432
    restart: on-failure:3

volumes:
  db_data:

networks:
  backend-network:
    driver: bridge
