version: 3

vars:
  ENV_FILE_LOCAL: "local.env"
  APP_SERVICE: "backend"
  DB_SERVICE: "database"

tasks:
  run:
    desc: "Inicia a aplicação em um container Docker (com dependências)."
    deps: [build, docker-up]

  build:
    desc: "Executa uma build limpa da aplicação."
    cmds:
      - "./gradlew clean"
      - "./gradlew build -x test"

  docker-up:
    desc: "Inicia todos os containers Docker definidos."
    cmd: "docker compose --env-file {{.ENV_FILE_LOCAL}} up --detach"

  docker-up-database:
    desc: "Inicia apenas o container do banco de dados."
    cmd: "docker compose up --detach {{.DB_SERVICE}}"

  docker-down:
    desc: "Para todos os containers Docker."
    cmd: "docker compose down"

  logs-backend:
    desc: "Mostra os logs do container da aplicação."
    cmd: "docker compose logs --follow {{.APP_SERVICE}}"

  logs-database:
    desc: "Mostra os logs do container do banco de dados."
    cmd: "docker compose logs --follow {{.DB_SERVICE}}"
