services:
  backend-app:
    container_name: sabores-conectados-backend-app
    build:
      dockerfile: Dockerfile
      context: ./
    networks:
      - backend-network
    ports:
      - 8081:8080
    restart: on-failure

networks:
  backend-network:
    driver: bridge
